# General settings 
rundir: "NA" # Defines where the raw uploads are placed.

samplesheet: "NA"
human_reference: "/project/ClinicalMicrobio/faststorage/database/GRCh38.p14_genomic.fna"
emu_db: "/project/ClinicalMicrobio/faststorage/database/emu_16s"
live_analysis: False
