name: report
channels:
  - conda-forge
  - bioconda
dependencies:
 - r-tidyverse = 2.0.0
 - r-reshape2 = 1.4.4
 - r-kableextra = 1.4.0
 - r-viridis = 0.6.5
 - r-readxl = 1.4.3
 - r-knitr = 1.46
 - r-base = 4.3.1

