# [--snakefile FILE] 
cores: 64
# [--local-cores N] 
configfile: "config.yaml"

# [--directory DIR] 
#keep-going: true 
rerun-incomplete: true
# [--shadow-prefix DIR] 
# [--reason] 
latency-wait: 30 # seconds
# [--max-jobs-per-second MAX_JOBS_PER_SECOND] 
# [--greediness GREEDINESS] 
# [--runtime-profile FILE] 
show-failed-logs: true

executor: slurm
slurm-logdir: logs

default-resources:
  slurm_account: "ClinicalMicrobio"
  cpus_per_task: 8
  runtime: 600 # minutes... hopefully
  mem_mb: 16000

# [--jobscript SCRIPT] 
jobname: "{name}.{jobid}.snakejob.sh" 
#use-conda: true
use-singularity: true
# [--conda-prefix DIR] 


printshellcmds: True
